version: '3.8'

services:
  db:
    build: ./MysqlDB
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bluechat_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    networks:
      - app-network

  api:
    build:
      context: ./../
      dockerfile: Docker/Api/Dockerfile
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user_password
      - DATABASE_NAME=bluechat_db
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge
